GET http://localhost:3000/unidade/
###

GET http://localhost:3000/quadra/64fd448dda6caaa754abcdfc
###

POST http://localhost:3000/quadra
###

DELETE http://localhost:3000/quadra/652fddc51bd65be62e3ee426
###

PUT http://localhost:3000/quadra/651e086ecc538deb3376f66d
Content-Type: application/json

{
    "cod_Quadra":"Q?",
    "nome":"Quadra?",
    "letra":"Q?",
    "cod_Unidade":"u3"
}
###

GET http://localhost:3000/unidade
###

GET http://localhost:3000/unidade/652fdd4447eaf7dde86a4ef7
###

POST http://localhost:3000/unidade
Content-Type: application/json

{
  "cod_Unidade": "u3",
  "nome_Unidade": "Unidade 3",
  "times": ["t7", "t8"],
  "quadras": ["q7", "q8"]
}
###

DELETE http://localhost:3000/unidade/652fdcb49c5c8478cba57258
###

PUT http://localhost:3000/unidade/652fdcb49c5c8478cba57258
Content-Type: application/json

{
  "cod_Unidade": "u3",
  "nome_Unidade": "Unidade 3",
  "times": ["t7", "t8"],
  "quadras": ["q7", "q8"]
}
